import blockContent from "./blockContent";
import category from "./category";
import post from "./post";
import author from "./author";
import seo from "./seo";
import {footer} from "./footer";
import {hero} from "./hero";
import {menu, menuItem}  from "./menu";
import { heroCard ,heroCardArray} from "./card";
import { pageContent } from "./PageContent";
export const schemaTypes = [post,heroCardArray, heroCard,author, category, blockContent, seo, menu, menuItem, footer,hero,pageContent];
